openapi: 3.0.0
info:
  title: NoteNet API
  version: 0.0.1
paths:
  /registration:
    put:
      summary: Создание нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Пользователь создан успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    boolean
        '409':
          description: Пользователь с такой почтой уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    boolean
        '500':
          description: Пользователь с такой почтой уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    boolean