openapi: 3.0.0
info:
  title: NoteNet API
  version: 0.0.1
  description: Java Spring Boot бэкенд для NoteNet
tags:
  - name: Пользователи
    description: Операции с пользователями
  - name: Заметки
    description: Операции с заметками
paths:
  /registration:
    put:
      summary: Создание нового пользователя
      tags:
        - Пользователи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@example.com
                  format: email
                password:
                  type: string
                  example: examplepassword
            example:
              email: 'example@example.com'
              password: '12345678'
      responses:
        '201':
          description: Пользователь создан успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: boolean
                    example: true
              example:
                res: true
        '409':
          description: Пользователь с такой почтой уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: boolean
                    example: false
              example:
                res: false
        '500':
          description: Пользователь с такой почтой уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: boolean
                    example: false
              example:
                res: false